version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3002:5432"
    volumes: # Added to ensure data persistence for the db
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "3003:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on: # Added to ensure db is ready before pgadmin starts
      - db

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "3004:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
    volumes:
      - ./:/app
    depends_on:
      - nextjs
      # - db # sonar-scanner doesn't directly depend on db
      # - pgadmin # sonar-scanner doesn't directly depend on pgadmin
      - sonarqube


volumes:
  pgdata:
